networks:
  meridyn_pharma:
    driver: bridge

volumes:
  pg_data: null

services:
  nginx:
    networks:
      - meridyn_pharma
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - ${PORT:-8000}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    depends_on:
      - web
    restart: always

  web:
    networks:
      - meridyn_pharma
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: ${COMMAND:-sh ./resources/scripts/entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - '.:/code'
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:17
    networks:
      - meridyn_pharma
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  
  redis:
    image: redis
    networks:
      - meridyn_pharma